name: Coverage Check

on:
  push:
    branches:
      - main  # Adjust as per your branch
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Use the preferred Java distribution

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests and Generate Coverage Report
        run: mvn test jacoco:report

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: target/site/jacoco/jacoco.xml  # Path to the coverage report file



