name: Coverage Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Change this if you're using a different Java version

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests and Generate Coverage Report
        run: mvn test jacoco:report

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: target/site/jacoco/jacoco.xml  # Path to the coverage report file
